// GENERATED by scripts/sync-knowledge.ts from website-v2. Do not edit by hand.
// Synced 2026-09-30.

export const HUB_URL = "https://dailyfriend.co.uk";

/** The hub's free tool that takes names and details out of a document. */
export const ANONYMISER_URL = "https://anonymiser.dailyfriend.co.uk";

export interface ToolFact {
  id: string;
  name: string;
  maker: string;
  category: string;
  summary: string;
  hosting: string;
  trainsOnData: string;
  dpa: string;
  watchOut: string[];
  checked: string;
}

export interface UseFact {
  id: string;
  title: string;
  /** good: usually no personal data. care: personal data, needs a DPA and DPIA. not-yet: do not. */
  readiness: string;
  area: string;
}

export const TOOLS: ToolFact[] = [
  {
    "id": "chatgpt",
    "name": "ChatGPT",
    "maker": "OpenAI",
    "category": "assistant",
    "summary": "A general AI assistant for drafting, summarising and rewording text. Only the Business and Enterprise plans come with a data processing agreement.",
    "hosting": "Not stated for the free, personal or Business plans. Enterprise can choose data residency in one of ten regions, the UK among them.",
    "trainsOnData": "depends",
    "dpa": "depends",
    "watchOut": [
      "Free and personal plans train on what you type unless the opt-out is switched on, and it is off until someone does it. Treat them as public and never enter anything about a person you support.",
      "No plan below Business carries SOC 2, ISO certification, UK data residency or a data processing agreement. A personal Plus account is not a lawful place for care records."
    ],
    "checked": "2026-09-21"
  },
  {
    "id": "claude",
    "name": "Claude",
    "maker": "Anthropic",
    "category": "assistant",
    "summary": "A general AI assistant for drafting, summarising and working through long documents. A data processing agreement comes with the Team and Enterprise plans.",
    "hosting": "Not stated. Anthropic publishes no UK data residency option, and its subprocessor list sits behind a request form.",
    "trainsOnData": "depends",
    "dpa": "depends",
    "watchOut": [
      "On personal plans, whether your chats train future models is a setting someone picked at sign-up. Check it before you trust it, and treat those accounts as public either way.",
      "The certifications only cover Team, Enterprise and the API. Free, Pro and Max do not appear in Anthropic's own scope table at all."
    ],
    "checked": "2026-09-21"
  },
  {
    "id": "google-gemini",
    "name": "Google Gemini",
    "maker": "Google",
    "category": "assistant",
    "summary": "A general AI assistant that also sits inside Gmail and Google Docs. Personal and Workspace accounts are governed completely differently.",
    "hosting": "Not stated for personal accounts. Workspace customers can restrict Gemini processing to the US or the EU. There is no UK-only option, and Gemini Notebook is excluded from data region settings altogether.",
    "trainsOnData": "depends",
    "dpa": "depends",
    "watchOut": [
      "On a personal account, Google says a subset of chats is read by human reviewers, and those are kept for up to three years. Deleting the chat does not remove them. Never type anything about a person you support into a personal account.",
      "Staff often have both a personal Google account and a work one, and the two look almost identical on screen. Check which one is signed in before trusting any of the Workspace protections."
    ],
    "checked": "2026-09-21"
  },
  {
    "id": "grammarly",
    "name": "Grammarly",
    "maker": "Superhuman Platform Inc. (formerly Grammarly)",
    "category": "writing",
    "summary": "Checks spelling, grammar and tone as you type, and rewrites text in plainer English. Now owned and run by Superhuman.",
    "hosting": "Amazon Web Services in the US East region.",
    "trainsOnData": "opt-out",
    "dpa": "depends",
    "watchOut": [
      "It works by reading what you type, wherever you type it, including inside your care system if the browser extension is installed. Decide where it is allowed to run before you roll it out.",
      "Whether your text trains its models is a setting, and the policy applies the same control to free and paid users. Check it rather than assuming a paid plan turns it off."
    ],
    "checked": "2026-09-21"
  },
  {
    "id": "magic-notes",
    "name": "Magic Notes",
    "maker": "Beam",
    "category": "transcription",
    "summary": "Records a social care conversation and drafts the assessment, summary and actions. Built for social care, processed in the UK, and used by several English councils.",
    "hosting": "The United Kingdom. Councils using it state that all information processed by Magic Notes is processed in the UK.",
    "trainsOnData": "no",
    "dpa": "unknown",
    "watchOut": [
      "Recording a conversation with someone you support needs a lawful basis and, in almost all cases, telling them. Several councils published a privacy notice before switching it on, which is the standard to copy.",
      "Pricing is not published anywhere, so you cannot compare it without going to sales."
    ],
    "checked": "2026-09-21"
  },
  {
    "id": "microsoft-copilot",
    "name": "Microsoft Copilot",
    "maker": "Microsoft",
    "category": "assistant",
    "summary": "AI built into Word, Excel, Outlook and Teams, answering from your own files and email. Renamed from Microsoft 365 Copilot in 2026.",
    "hosting": "Processed in Microsoft 365. EU customers are covered by the EU Data Boundary, but the UK is outside it, so UK queries may be processed in the US, the EU or elsewhere unless you buy Advanced Data Residency.",
    "trainsOnData": "no",
    "dpa": "yes",
    "watchOut": [
      "It surfaces anything the member of staff can already open. If your SharePoint permissions are loose, Copilot turns that into a search engine. Fix permissions before you switch it on.",
      "The UK is not inside the EU Data Boundary. UK queries may be processed in the United States unless you buy Advanced Data Residency, which commissioners may ask about."
    ],
    "checked": "2026-09-21"
  },
  {
    "id": "otter",
    "name": "Otter",
    "maker": "Otter.ai",
    "category": "transcription",
    "summary": "Records and transcribes meetings, then writes a summary and action list. Otter's privacy policy says it trains its own AI on transcriptions.",
    "hosting": "Amazon Web Services in the United States.",
    "trainsOnData": "yes",
    "dpa": "unknown",
    "watchOut": [
      "Otter's own policy says it trains its AI on transcriptions that may contain personal information, with no plan-level exception and no opt-out that we could find. That is hard to square with recording anything about a person you support.",
      "Recordings are held on servers in the United States."
    ],
    "checked": "2026-09-21"
  }
];

export const USES: UseFact[] = [
  {
    "id": "care-plans",
    "title": "Drafting care and support plans",
    "readiness": "care",
    "area": "records"
  },
  {
    "id": "easy-read-letters",
    "title": "Making letters and leaflets easier to read",
    "readiness": "good",
    "area": "communications"
  },
  {
    "id": "eligibility-decisions",
    "title": "Deciding eligibility, risk or who gets a service",
    "readiness": "not-yet",
    "area": "referrals"
  },
  {
    "id": "family-updates",
    "title": "Writing updates for families",
    "readiness": "care",
    "area": "communications"
  },
  {
    "id": "funding-bids",
    "title": "Drafting funding bids and impact reports",
    "readiness": "good",
    "area": "bids-reports"
  },
  {
    "id": "incident-summaries",
    "title": "Summarising incidents for reports and reviews",
    "readiness": "care",
    "area": "records"
  },
  {
    "id": "policy-updates",
    "title": "Reviewing and rewriting policies",
    "readiness": "good",
    "area": "bids-reports"
  },
  {
    "id": "recruitment-adverts",
    "title": "Writing job adverts and interview questions",
    "readiness": "good",
    "area": "people"
  },
  {
    "id": "referral-summaries",
    "title": "Summarising long referral documents",
    "readiness": "care",
    "area": "referrals"
  },
  {
    "id": "rota-cover",
    "title": "Suggesting cover for rota gaps",
    "readiness": "care",
    "area": "scheduling"
  },
  {
    "id": "visit-notes",
    "title": "Turning spoken notes into visit records",
    "readiness": "care",
    "area": "records"
  },
  {
    "id": "wellbeing-check-ins",
    "title": "Automated wellbeing check-in calls",
    "readiness": "care",
    "area": "wellbeing"
  }
];

/** Hub pages the builder may link to, by path. */
export const PAGES: Record<string, string> = {
  "/tools": "AI tool directory",
  "/uses": "Ways to use AI, rated honestly",
  "/safe-use/check": "Can I use AI for this? A one-minute check",
  "/templates/prompts": "Prompt library",
  "/templates/glossary": "Plain-English glossary",
  "/guides/ai-and-self-directed-support": "AI and self-directed support: where it fits",
  "/guides/ai-in-social-care-alliance": "A sector alliance on AI in social care: what to know",
  "/guides/capacity-consent-and-ai": "Capacity, consent and AI",
  "/guides/charity-digital-skills-report-2026": "Charity Digital Skills Report 2026: what it says about AI",
  "/guides/dhsc-guidance-using-ai-in-adult-social-care": "The government's guidance on AI in adult social care: what it says and what it leaves out",
  "/guides/do-you-need-a-dpia": "Do you need a DPIA for an AI tool?",
  "/guides/free-vs-paid-ai-tools": "Free and paid AI tools: what happens to your data",
  "/guides/golden-rules": "The golden rules: using AI safely in care",
  "/guides/measuring-a-baseline": "Measuring an admin task before you change it",
  "/guides/paying-for-ai": "Paying for AI: what small providers should budget for",
  "/guides/questions-to-ask-a-supplier": "Questions to ask an AI supplier",
  "/guides/safeguarding-and-ai": "Safeguarding and AI",
  "/guides/spotting-ai-mistakes": "How to spot the mistakes AI makes",
  "/guides/telling-people-you-support": "Telling the people you support that you use AI",
  "/guides/tip-ask-what-it-is-unsure-about": "Tip: ask the tool what it is unsure about",
  "/guides/tip-use-made-up-details": "Tip: test prompts with a made-up person",
  "/guides/what-ai-is": "What AI is, and what it is not, in plain English",
  "/guides/what-cqc-says-about-ai": "What CQC says about AI, and what it does not",
  "/guides/writing-an-ai-use-policy": "Writing a one-page AI use policy",
  "/templates/ai-dpia": "AI data protection impact assessment (DPIA)",
  "/templates/ai-use-policy": "One-page AI use policy",
  "/templates/board-briefing": "AI questions for boards and trustees",
  "/templates/never-paste-this": "\"Never paste this\" staff poster",
  "/templates/supplier-questions": "AI supplier question sheet",
  "/templates/telling-people-letter": "Letter telling people you use AI",
  "/templates/time-tracker": "Admin time tracker",
  "/tools/chatgpt": "ChatGPT in the tool directory",
  "/tools/claude": "Claude in the tool directory",
  "/tools/google-gemini": "Google Gemini in the tool directory",
  "/tools/grammarly": "Grammarly in the tool directory",
  "/tools/magic-notes": "Magic Notes in the tool directory",
  "/tools/microsoft-copilot": "Microsoft Copilot in the tool directory",
  "/tools/otter": "Otter in the tool directory",
  "/uses/care-plans": "Drafting care and support plans",
  "/uses/easy-read-letters": "Making letters and leaflets easier to read",
  "/uses/eligibility-decisions": "Deciding eligibility, risk or who gets a service",
  "/uses/family-updates": "Writing updates for families",
  "/uses/funding-bids": "Drafting funding bids and impact reports",
  "/uses/incident-summaries": "Summarising incidents for reports and reviews",
  "/uses/policy-updates": "Reviewing and rewriting policies",
  "/uses/recruitment-adverts": "Writing job adverts and interview questions",
  "/uses/referral-summaries": "Summarising long referral documents",
  "/uses/rota-cover": "Suggesting cover for rota gaps",
  "/uses/visit-notes": "Turning spoken notes into visit records",
  "/uses/wellbeing-check-ins": "Automated wellbeing check-in calls"
};
