// Copies the facts this tool relies on from the website's content, so there is
// one checked source for them. Run after the website's tool directory or use
// pages change, and commit the result:
//
//   npm run sync                          website-v2 next to Tools/
//   npm run sync -- --site=/path/to/website-v2
//
// Only fields the builder uses are copied. Placeholder and draft entries are
// left out, because an unchecked fact must never reach a policy.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const here = path.dirname(fileURLToPath(import.meta.url));
const arg = process.argv.find((a) => a.startsWith('--site='));
const site = path.resolve(arg ? arg.slice('--site='.length) : path.join(here, '../../../website-v2'));
const out = path.join(here, '../src/shared/knowledge.generated.ts');

function frontMatter(file: string): Record<string, unknown> {
  const text = fs.readFileSync(file, 'utf8');
  const m = /^---\n([\s\S]*?)\n---/.exec(text);
  if (!m?.[1]) throw new Error(`No front matter in ${file}`);
  return parse(m[1]) as Record<string, unknown>;
}

function entries(dir: string, ext: string): { id: string; file: string }[] {
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(ext) && !f.startsWith('_'))
    .sort()
    .map((f) => ({ id: f.slice(0, -ext.length), file: path.join(dir, f) }));
}

const siteConfig = fs.readFileSync(path.join(site, 'src/config.ts'), 'utf8');
const siteUrl = /export const SITE_URL = '([^']+)'/.exec(siteConfig)?.[1];
if (!siteUrl) throw new Error('SITE_URL not found in website-v2/src/config.ts');
const anonymiserUrl = /export const ANONYMISER_URL = '([^']+)'/.exec(siteConfig)?.[1];
if (!anonymiserUrl) throw new Error('ANONYMISER_URL not found in website-v2/src/config.ts');

/**
 * Pages built from code rather than content, so their titles are set here.
 * Each must still exist on the site, or the sync fails rather than link to a
 * page that has gone.
 */
const STATIC_PAGES: Record<string, string> = {
  '/tools': 'AI tool directory',
  '/uses': 'Ways to use AI, rated honestly',
  '/safe-use/check': 'Can I use AI for this? A one-minute check',
  '/templates/prompts': 'Prompt library',
  '/templates/glossary': 'Plain-English glossary',
};
for (const p of Object.keys(STATIC_PAGES)) {
  const base = path.join(site, 'src/pages', p);
  if (!fs.existsSync(`${base}.astro`) && !fs.existsSync(path.join(base, 'index.astro'))) {
    throw new Error(`Hub page ${p} no longer exists in website-v2/src/pages`);
  }
}

interface ToolYaml {
  name: string;
  maker: string;
  category: string;
  summary: string;
  data: { hosting: string; trainsOnData: string; dpa: string };
  watchOut: string[];
  checked: string | Date;
  placeholder?: boolean;
  draft?: boolean;
}

const tools = entries(path.join(site, 'src/content/tools'), '.yaml')
  .map(({ id, file }) => ({ id, data: parse(fs.readFileSync(file, 'utf8')) as ToolYaml }))
  .filter(({ data }) => !data.placeholder && !data.draft)
  .map(({ id, data }) => ({
    id,
    name: String(data.name),
    maker: String(data.maker),
    category: String(data.category),
    summary: String(data.summary),
    hosting: String(data.data.hosting),
    trainsOnData: String(data.data.trainsOnData),
    dpa: String(data.data.dpa),
    watchOut: data.watchOut.slice(0, 2),
    checked: new Date(data.checked).toISOString().slice(0, 10),
  }));

const uses = entries(path.join(site, 'src/content/uses'), '.md')
  .map(({ id, file }) => ({ id, fm: frontMatter(file) }))
  .filter(({ fm }) => !fm.placeholder && !fm.draft)
  .map(({ id, fm }) => ({
    id,
    title: String(fm.title),
    readiness: String(fm.readiness),
    area: String(fm.area),
  }));

/** Published pages only: placeholders and drafts are not on the live site. */
const published = (kind: string) =>
  entries(path.join(site, `src/content/${kind}`), '.md')
    .map(({ id, file }) => ({ id, fm: frontMatter(file) }))
    .filter(({ fm }) => !fm.placeholder && !fm.draft)
    .map(({ id, fm }) => ({ path: `/${kind}/${id}`, title: String(fm.title) }));

const pages = [
  ...Object.entries(STATIC_PAGES).map(([p, title]) => ({ path: p, title })),
  ...published('guides'),
  ...published('templates'),
  ...tools.map((t) => ({ path: `/tools/${t.id}`, title: `${t.name} in the tool directory` })),
  ...uses.map((u) => ({ path: `/uses/${u.id}`, title: u.title })),
];

const body = `// GENERATED by scripts/sync-knowledge.ts from website-v2. Do not edit by hand.
// Synced ${new Date().toISOString().slice(0, 10)}.

export const HUB_URL = ${JSON.stringify(siteUrl)};

/** The hub's free tool that takes names and details out of a document. */
export const ANONYMISER_URL = ${JSON.stringify(anonymiserUrl)};

export interface ToolFact {
  id: string;
  name: string;
  maker: string;
  category: string;
  summary: string;
  hosting: string;
  trainsOnData: string;
  dpa: string;
  watchOut: string[];
  checked: string;
}

export interface UseFact {
  id: string;
  title: string;
  /** good: usually no personal data. care: personal data, needs a DPA and DPIA. not-yet: do not. */
  readiness: string;
  area: string;
}

export const TOOLS: ToolFact[] = ${JSON.stringify(tools, null, 2)};

export const USES: UseFact[] = ${JSON.stringify(uses, null, 2)};

/** Hub pages the builder may link to, by path. */
export const PAGES: Record<string, string> = ${JSON.stringify(Object.fromEntries(pages.map((p) => [p.path, p.title])), null, 2)};
`;

fs.writeFileSync(out, body);
console.log(
  `Wrote ${tools.length} tools, ${uses.length} uses, ${pages.length} pages to ${path.relative(process.cwd(), out)}`,
);
