// Copies the facts this tool relies on from the website's content, so there is
// one checked source for them. Run after the website's tool directory or use
// pages change, and commit the result:
//
//   npm run sync                          website-v2 next to Tools/
//   npm run sync -- --site=/path/to/website-v2
//
// Only fields the builder uses are copied. Placeholder and draft entries are
// left out, because an unchecked fact must never reach a policy.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

const here = path.dirname(fileURLToPath(import.meta.url));
const arg = process.argv.find((a) => a.startsWith('--site='));
const site = path.resolve(arg ? arg.slice('--site='.length) : path.join(here, '../../../website-v2'));
const out = path.join(here, '../src/shared/knowledge.generated.ts');

function frontMatter(file: string): Record<string, unknown> {
  const text = fs.readFileSync(file, 'utf8');
  const m = /^---\n([\s\S]*?)\n---/.exec(text);
  if (!m?.[1]) throw new Error(`No front matter in ${file}`);
  return parse(m[1]) as Record<string, unknown>;
}

function entries(dir: string, ext: string): { id: string; file: string }[] {
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(ext) && !f.startsWith('_'))
    .sort()
    .map((f) => ({ id: f.slice(0, -ext.length), file: path.join(dir, f) }));
}

const siteConfig = fs.readFileSync(path.join(site, 'src/config.ts'), 'utf8');
const siteUrl = /export const SITE_URL = '([^']+)'/.exec(siteConfig)?.[1];
if (!siteUrl) throw new Error('SITE_URL not found in website-v2/src/config.ts');

interface ToolYaml {
  name: string;
  maker: string;
  category: string;
  summary: string;
  data: { hosting: string; trainsOnData: string; dpa: string };
  watchOut: string[];
  checked: string | Date;
  placeholder?: boolean;
  draft?: boolean;
}

const tools = entries(path.join(site, 'src/content/tools'), '.yaml')
  .map(({ id, file }) => ({ id, data: parse(fs.readFileSync(file, 'utf8')) as ToolYaml }))
  .filter(({ data }) => !data.placeholder && !data.draft)
  .map(({ id, data }) => ({
    id,
    name: String(data.name),
    maker: String(data.maker),
    category: String(data.category),
    summary: String(data.summary),
    hosting: String(data.data.hosting),
    trainsOnData: String(data.data.trainsOnData),
    dpa: String(data.data.dpa),
    watchOut: data.watchOut.slice(0, 2),
    checked: new Date(data.checked).toISOString().slice(0, 10),
  }));

const uses = entries(path.join(site, 'src/content/uses'), '.md')
  .map(({ id, file }) => ({ id, fm: frontMatter(file) }))
  .filter(({ fm }) => !fm.placeholder && !fm.draft)
  .map(({ id, fm }) => ({
    id,
    title: String(fm.title),
    readiness: String(fm.readiness),
    area: String(fm.area),
  }));

const guideIds = entries(path.join(site, 'src/content/guides'), '.md');
const templateIds = entries(path.join(site, 'src/content/templates'), '.md');
const pages = [
  ...guideIds.map(({ id, file }) => ({ path: `/guides/${id}`, title: String(frontMatter(file).title) })),
  ...templateIds.map(({ id, file }) => ({
    path: `/templates/${id}`,
    title: String(frontMatter(file).title),
  })),
  ...tools.map((t) => ({ path: `/tools/${t.id}`, title: `${t.name} in the tool directory` })),
];

const body = `// GENERATED by scripts/sync-knowledge.ts from website-v2. Do not edit by hand.
// Synced ${new Date().toISOString().slice(0, 10)}.

export const HUB_URL = ${JSON.stringify(siteUrl)};

export interface ToolFact {
  id: string;
  name: string;
  maker: string;
  category: string;
  summary: string;
  hosting: string;
  trainsOnData: string;
  dpa: string;
  watchOut: string[];
  checked: string;
}

export interface UseFact {
  id: string;
  title: string;
  /** good: usually no personal data. care: personal data, needs a DPA and DPIA. not-yet: do not. */
  readiness: string;
  area: string;
}

export const TOOLS: ToolFact[] = ${JSON.stringify(tools, null, 2)};

export const USES: UseFact[] = ${JSON.stringify(uses, null, 2)};

/** Hub pages the action plan may link to, by path. */
export const PAGES: Record<string, string> = ${JSON.stringify(Object.fromEntries(pages.map((p) => [p.path, p.title])), null, 2)};
`;

fs.writeFileSync(out, body);
console.log(
  `Wrote ${tools.length} tools, ${uses.length} uses, ${pages.length} pages to ${path.relative(process.cwd(), out)}`,
);
